### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-7#25]
*Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

### README.md file

- [ ] Summary in README should include high-level interpretation of analysis findings,
as well 1-2 sentences on what they might mean (at least at a high-level). **-1**

### Analysis methods & results

- [ ] The data should be reproducibly downloaded from it's source using code in the analysis code document,
and a copy saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**
- [ ] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. **-1**

### Dockerfile

- [ ] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned.
Failing to do this, means that each time the Docker image is built in the future,
the latest version of the base image will be used.
The latest version of the base image will very likely change over time,
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-1**
- [ ] The Dockefile could be simplified. For instance, multiple RUN instructions could be merged into one. **-1**

### Project organization

- [ ] The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**
- [ ] Files such as `.DS_Store` should not be committed. **-1**

### GitHub Project board

- [ ] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labelled and linked to milestones. **-1**

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **-5**

### CONTRIBUTING.md

- [ ] Contributing documentation should reflect all the ways people can contribute to the project
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,
as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**
- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

**Comment by jossiej00** [comment]
have created GitHub Issue Milestones

**Comment by jossiej00** [comment]
have rearrange the datasets in folder

**Comment by jossiej00** [comment]
done project organization

**Comment by jossiej00** [comment]
done github project board

**Comment by sasiburi** [comment]
done revision of Dockerfile

**Comment by jossiej00** [comment]
done revision of  contributing.md
