### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-7#53]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] There are cases of functions that are too big and could be improved by defining utility functions. **- 1**

`finalModel`

- [ ] Functions do not follow a consistent style. **-1**

For instance, some funtions use snake_case and other funtions use camelCase.

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 3**

`stdAcc`, `pre_process`, `line_plot`

- [ ] Ther is commented out code. **- 1**

`line_plot`

### Functions are well documented

- [ ] Documentation does not follow a consistent style. **- 1**

Some functions use docstring, others use comments, etc.

- [ ] One or more documentations are missing one or more required elements (title, argument, returned, example). **- 1.5**

`finaModel`, `pre_process`

- [ ] One or more documentations could be improved through additional proofreading (i.e., spelling and grammatical errors are present). **- 0.5**

`para_optimize` has the documentation comments at the wrong place.

### Helper data for tests is tractable and reproducible

- [ ] The data used could be a simple hand made data instead of the the original dataset.  **- 3**

`finalModel`, `pre_process`, `para_optimize`

### Tests are well documented

- [ ] There are cases of tests that have no or almost no documentation. **- 1**

`std_acc`

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 2 expected input. **- 1**

`pre_process`, `para_optimize`

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 3**

`finalModel`, `stdAcc`, `pre_process`, `para_optimize`

- [ ] There is commented out code. **- 2**

`stdAcc`, `para_optimize`

- [ ] There are cases of functions that do not test at least 1 wrong input. **- 2**

`stdAcc`, `pre_process`

### GitHub release

- [ ] Please provide the link to the release as https://github.com/DSCI-310/REPOSITORY/tree/VERSION (replacing REPOSITORY and VERSION with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Could not run the analysis because the instructions provide wrong commands. **- 3**

`<tag name>` in `docker pull sasiburi/dsci-310-group-7:<tag name>`

`image_id/name` in `docker run -p 8888:8888 image_id/name`

- [ ] I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**

You should also have instruction to clone the repository inside the container

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

**Comment by luckyberen** [comment]
Fixed issues in para_parameter and its test.

**Comment by luckyberen** [comment]
Union the function name style in the package code

**Comment by luckyberen** [comment]
Unify the comments style in the functions.

**Comment by sasiburi** [comment]
Add input type check for line_plot.

**Comment by jossiej00** [comment]
fixed docker command

**Comment by jossiej00** [comment]
I have checked the advisement suggestions on functions except `finalModel`. Everything should be fine
