### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-7#98]
## Rubric
- 25 / 25: Analysis code is abstracted to four (or more) scripts which take command line arugments and save analysis artifacts (e.g., figures and data for tables).
- 17 / 25: Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- 23 / 25: A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- 2 / 2: Dependencies have been updated (so it include the test libraries)
- 1 / 2: Project file and directory structure organization
- 2 / 2: GitHub Project board
- 2 / 2: GitHub Issue Milestones
- 2 / 2: Follows GitHub flow version control workflow
- 2 / 2: GitHub release
- 9 / 13: Analysis can be run reproducibly using documentation provided in the README.

## Commonly provided feedback

Recommended to open an issue in the project's repository to provide this feedback so students can act on it.
In milestone 4, these things will be regraded as part of the final grade for the project.
Bolded points indicate how many points should be taken off the rubric for each of these.
These numbers do not need to be included in the GitHub issue.

Text to copy and paste into GitHub issue before providing specific comments:

*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

Observation: I analyzed the `.Rmd` file due to time limitations.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use markup language syntax to reference tables and figures so that the correct table and figure numbers are automatically used **- 4**

You have captions for tables and figures but don't cross-reference them except for one case.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document **- 4**

There are hard coded values such as "The best accuracy was with value 0.9047619047619048 with maximum depth = 5."

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

`.virtual_documents/`

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] The docker version is not clear. For instance, `sasiburi/dsci-310-group-7:v3.0.0` does not exist. **- 1**

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment but there was an attempt in installing the dependencies. **-3**

Consider basing your dockerfile from `jupyter/datascience-notebook` image instead of using both `jupyter/scipy-notebook` and `jupyter/r-notebook`

Dependency error that I got:

(base) jovyan@3074f35a0eb2:~/work/DSCI-310-Group-7$ jupyter-book build analysis/
bash: jupyter-book: command not found

(base) jovyan@3074f35a0eb2:~/work/DSCI-310-Group-7$ make all
python src/read_data_script.py data/raw/zoo.data data/processed/zoo.csv
Traceback (most recent call last):
  File "/home/jovyan/work/DSCI-310-Group-7/src/read_data_script.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
make: *** [Makefile:10: data/processed/zoo.csv] Error 1

Moreover, I also got this error:

I think you did not set up tinytex correctly.

from `make all`

jb build analysis/ --builder pdflatex
Running Jupyter-Book v0.12.1
Source Folder: /home/jovyan/work/DSCI-310-Group-7/analysis
Config Path: /home/jovyan/work/DSCI-310-Group-7/analysis/_config.yml
Output Path: /home/jovyan/work/DSCI-310-Group-7/analysis/_build/latex
Running Sphinx v4.5.0
[etoc] Changing master_doc to 'contents'
loading pickled environment... checking for /home/jovyan/work/DSCI-310-Group-7/analysis/references.bib in bibtex cache... up to date
done
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
sphinx-jupyterbook-latex v0.4.6:engine='xelatex', toplevel_section='chapter', imgconverter='sphinx.ext.imgconverter', show_tocs='list'
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing python.tex... contents intro analysis discussion references
resolving references...
/home/jovyan/work/DSCI-310-Group-7/analysis/analysis.ipynb:30002: WARNING: 'myst' reference target not found: "https://archive-beta.ics.uci.edu/ml/datasets/zoo"
done
writing... done
copying images... [100%] ../results/figures/dt_accuracy.png
copying TeX support files... copying TeX support files...
done
build succeeded, 1 warning.

The LaTeX files are in analysis/_build/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
Finished generating latex for book...
Converting book latex into PDF...
make[1]: Entering directory '/home/jovyan/work/DSCI-310-Group-7/analysis/_build/latex'
latexmk -pdf -dvi- -ps-  'python.tex'
make[1]: latexmk: No such file or directory
make[1]: *** [Makefile:29: python.pdf] Error 127
make[1]: Leaving directory '/home/jovyan/work/DSCI-310-Group-7/analysis/_build/latex'
Traceback (most recent call last):
  File "/opt/conda/bin/jb", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_book/cli/main.py", line 323, in build
    builder_specific_actions(
  File "/opt/conda/lib/python3.9/site-packages/jupyter_book/cli/main.py", line 608, in builder_specific_actions
    _error("Error: Failed to build pdf")
  File "/opt/conda/lib/python3.9/site-packages/jupyter_book/utils.py", line 48, in _error
    raise kind(box)
RuntimeError:
===============================================================================

Error: Failed to build pdf

===============================================================================

make: *** [Makefile:32: analysis/_build/latex/python.pdf] Error 1

another erro from `Rscript -e "rmarkdown::render('doc/zoo_analysis.Rmd', c('bookdown::html_document2', 'bookdown::pdf_document2'))"`

output file: zoo_analysis.knit.md

/opt/conda/bin/pandoc +RTS -K512m -RTS zoo_analysis.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output zoo_analysis.tex --lua-filter /opt/conda/lib/R/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /opt/conda/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /opt/conda/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --table-of-contents --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --variable graphics --wrap preserve --variable 'geometry:margin=1in' --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc
! LaTeX Error: File `lmodern.sty' not found.

! Emergency stop.
<read *>

Error: LaTeX failed to compile zoo_analysis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See zoo_analysis.log for more info.
Execution halted
