### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-7#99]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] There are no instructions linking the feedback to the changes in the source code. **- 5**

### Addressed feedback given by the teaching team from milestone 2

- [ ] There are no instructions linking the feedback to the changes in the source code. **- 5**

### Dependencies have been updated (so it include the newly created external software package)

- [ ] Dependencies have been updated but do not work in the final image. **- 0.5**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 0.5**

`.virtual_documents/`

### GitHub Project board

- [ ] There is no project board. **-1**

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **- 1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got a severe error while trying to reproduce the analysis. **- 5**

You are missing the dependencies,

```
(base) jovyan@04a6818cd807:~/work$ make all
python src/read_data_script.py data/raw/zoo.data data/processed/zoo.csv
Traceback (most recent call last):
  File "/home/jovyan/work/src/read_data_script.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
make: *** [Makefile:10: data/processed/zoo.csv] Error 1
```
